[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "world_engine"
version = "1.5.0"
requires-python = ">=3.10"
dependencies = [
  "taehv @ https://github.com/madebyollin/taehv/archive/7dc60ec6601af2e668e31bc70acc4cb3665e4c22.zip",
  "torch==2.9.1",
  "einops",
  "tensordict==0.10.0",
  "transformers>=4.49.0",
  "ftfy",
  "diffusers",
  "huggingface-hub>=0.36.0",
  "omegaconf",
  "accelerate>=1.1.1",
  # Triton (platform-specific)
  "triton==3.5.1; sys_platform == 'linux'",
  "triton-windows==3.5.1.post24; sys_platform == 'win32'",
  "gemlite @ https://github.com/dropbox/gemlite/archive/ebfcc197d694acd4ca8dfaadf5fceb3570401df3.zip",
]

[tool.setuptools]
packages = [
  "world_engine",
  "world_engine.model",
]

[tool.setuptools.package-dir]
world_engine = "src"

[dependency-groups]
dev = [
  "pytest",
  "pytest-benchmark",
  "opencv-python",
  "imageio[pyav]",
  "numpy",
]
